### ISSUE TITLE
Element type is invalid: expected a string but got: object

### ISSUE THREAD

**Issue by hasen6** [brentvatne/react-native-linear-gradient#100]
Getting this error with:

    "react": "^15.2.1",
    "react-native": "^0.29.2",
    "react-native-linear-gradient": "^1.5.12"

Error:

`Element type is invalid: expected a string (for build in components) or a class/function (for composite components) but got: object. Check the render method.`

By the looks of things this module is no longer supported which is a shame since its so great I use it in almost every project. The more they update React Native, the more modules become incompatible and most are not updated accordingly.

**Comment by mkdotcom** [comment]
var LinearGradient = require('react-native-linear-gradient').default;

**Comment by hasen6** [comment]
Yes that was it, I tried to use it with the old code just before the readme was updated here with the new usage. Thanks.
