### ISSUE TITLE
Can this be used to create a gradient overlay on an image ?

### ISSUE THREAD

**Issue by antani** [brentvatne/react-native-linear-gradient#14]
The following does not create a gradient on the image.
````html
  <LinearGradient
                locations={locations}
                colors={colors}
               >
                <ImageView
                defaultSource={require('image!default-bg')}
                source={{
                  uri: imgURL
                }}
                />
              </LinearGradient>
````

**Comment by brentvatne** [comment]
I would put the LinearGradient and Image inside of a View, then position the LinearGradient with absolute positioning to top: 0, bottom: 0, left: 0, right: 0, and include `transparent` in the colors somewhere

**Comment by nickhudkins** [comment]
@antani, closing this as this is intended functionality, let me know if you need anything beyond what @brentvatne provided, but that will do what you described :)

**Comment by pedramsaleh** [comment]
I had to put the `<LinearGradient>` inside the image tags, and add `backgroundColor: "transparent"` to its style to put a gradient on top of the image.  Hope that helps :)

**Comment by antani** [comment]
Works fine. Thanks.

**Comment by carlosramireziii** [comment]
@pedramsaleh Would you mind including a working code sample here for reference

**Comment by pedramsaleh** [comment]
It was something like this: 

```
<Image style={styles.image} source={{uri: this.props.image}} resizeMode="cover">
    <LinearGradient  colors={["transparent", "black"]} locations={[0.4,1.2]} style={styles.linearGradient}>
// other image overlay code (text etc.)
    </LinearGradient>
</Image>
```

The style object for LinearGradient was this:

```
linearGradient: {
        backgroundColor: "transparent",
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0
}
```

Hope that helps.

**Comment by nauticalcoder** [comment]
> @carlosramireziii
> 
> ```
> <Image style={styles.image} source={{uri: this.props.image}} resizeMode="cover">
>     <LinearGradient  colors={["transparent", "black"]} locations={[0.4,1.2]} style={styles.linearGradient}>
>     // other image overlay code (text etc.)
>     </LinearGradient>
> </Image>
> ```
This doesn't work now as the <Image /> component can't contain any children.

**Comment by sinxwal** [comment]
@carlosramireziii
You can do something like this:
`<ImageBackground
    style={styles.pic}
            source={...}
          >
          <LinearGradient
            colors={['#ffffff00', 'white']}
            style={{
              backgroundColor: 'transparent',
              position: 'absolute',
              top: 0,
              bottom: 0,
              left: 0,
              right: 0,
            }}
          />
        </ImageBackground>`

**Comment by Francois-vanderMerwe** [comment]
I managed to add a sort of blurred border to the top and bottom of an image using this: (#212225 is the colour of the screens background)

  return (
<View style={styles.fixedTop} pointerEvents='none'>
  <Image source={{ uri: reward.image }} style={styles.image}/>
  <LinearGradient
        colors={[
          '#212225',
          'transparent',
          'transparent',
          '#212225'
        ]}
        locations={[0, 0.05, 0.95, 1]}
        style={styles.linearGradient}
  />

</View>
  )


const styles = StyleSheet.create({
  fixedTop: {
    zIndex: 1,
    position: 'absolute',
    top: 0,
    width,
    height: 100,
    marginTop: 10
  },
  linearGradient: {
    width,
    height: 237,
    position: 'absolute'
  },
  image: {
    width: '100%',
    height: 237,
    opacity: 0.9
  }
})

**Comment by tushar-pandey-travelxp** [comment]
[sinxwal](https://github.com/sinxwal) 
USE 
<ImageBackgroud> instead of image
