### ISSUE TITLE
All I get is a red border

### ISSUE THREAD

**Issue by pedramsaleh** [brentvatne/react-native-linear-gradient#16]
I'm trying to use this to add a gradient on top of an image, but all I get is a red border around it

The code looks like this
````
<LinearGradient colors={["black", "transparent"]} start={[0.0, 0.25]} end={[0.5, 1.0]} style={styles.linearGradient}>  
    <Image style={styles.foodImage} source={this.props.image} resizeMode="cover">
    ...
    </Image>
</LinearGradient>

var styles = StyleSheet.create({
	linearGradient: {
        flex: 1,
        paddingLeft: 0,
        paddingRight: 0,
        borderRadius: 0,
      },
...
}
````
I didn't make it position: "absolute" like you suggested in the other issue about putting it over an image, because I want the images as a list and that would make them all stack on top of each other and only show the last one in the list.

I tried making the facebook button using the same code as in the example to see if it was just my code, but that just gives a similar thing (button with a red border) like this: 

![facebook_button](https://cloud.githubusercontent.com/assets/12803855/10152293/a33700be-661e-11e5-8bc8-bbd1efdaceff.PNG)

I'm pretty sure I added the library properly (see screenshot below), although I didn't see the step for adding BVLinearGradient.xcodeproj to the project (it says to add a file to Libraries, but doesn't say what file), though I assumed that's what it was and I did that anyway.

![xcode1](https://cloud.githubusercontent.com/assets/12803855/10152295/a340c842-661e-11e5-8d9f-ff2de030e914.PNG)

Am I doing something wrong?

**Comment by nickhudkins** [comment]
You want to add libBVLinearGradient.a to the 'MenYouDraft' project's build phases, rather than BVLinearGradient.xcodeproj.

That should get it working :)

**Comment by pedramsaleh** [comment]
I did add libBVLinearGradient.a to the build phases (see my screenshot above).  I was just saying that I had to add BVLinearGradient.xcodeproj to Libraries (which wasn't outlined in the instructions) to get libBVLinearGradient.a to appear in Xcode :)

**Comment by nickhudkins** [comment]
@pedramsaleh so is everything working properly now? The screenshot you posted shows the lib added to the wrong Build Phases, but perhaps that is just the wrong screenshot.

**Comment by pedramsaleh** [comment]
Yes it's working now.  You were right, I had it in the wrong build phase.  Thanks.

**Comment by nickhudkins** [comment]
Awesome, glad to hear it :+1:
