### ISSUE TITLE
Color to transparent

### ISSUE THREAD

**Issue by josebalius** [brentvatne/react-native-linear-gradient#2]
Any way to create a gradient that goes from black to transparent?

**Comment by brentvatne** [comment]
@josebalius - have you tried using 'transparent' as a color value?

**Comment by josebalius** [comment]
@brentvatne unfortunately for me, I keep getting a solid white color regardless of what color I put in, I must be missing something in the install. I looked at the screenshots and saw they were from the video component you made, not this one, maybe I'm missing a step? I have no errors or anything its just white background.

**Comment by marcshilling** [comment]
Working for me.

Specifying `colors={['transparent', 'rgba(0, 0, 0, 0.5)']}` gives me a linear gradient from 50% black to completely transparent

**Comment by brentvatne** [comment]
@marcshilling - nice, I actually forgot about this issue, thanks for that!

**Comment by paramaggarwal** [comment]
Wow, didn't know I could specify colours as `rgba(0, 0, 0, 0.5)` - super handy.

**Comment by yasserzubair** [comment]
Does this work on android too? I have been trying it this way. No luck

**Comment by aliy321** [comment]
anyone got it to work on android with transparent? i keep getting white background with transparent

**Comment by stanhughes** [comment]
Does any one have a solution for Android?  I am having the same issue.

**Comment by nihp** [comment]
I need to show the grey to grey color in linear gradient. But my simulator shows grey to black in iOS simulator. Is there is an option to change the color.

 ```
 width: 200,
    height: 15,
    widthShimmer: 0.7,
    duration: 1000,
    colorShimmer: ['#D0D0D0', '#c5c5c5', '#D0D0D0'],
    reverse: false,
    autoRun: false,
    visible: false,
    backgroundColorBehindBorder: 'white',
    hasBorder: false,
```

**Comment by mehdihussainmohammed9** [comment]
@marcshilling Thank u its working
