### ISSUE TITLE
Where is libBVLinearGradient.a?

### ISSUE THREAD

**Issue by jasecoop** [brentvatne/react-native-linear-gradient#20]
This is likely to be a stupid question, this is my first react-native app, bare with me.

I'm following the installation instructions, I've installed with npm and I can't find the file libBVLinearGradient.a anywhere.

Am I missing something?

**Comment by jadsonlourenco** [comment]
You follow the readme, all steps? You did the step 2, 3 and 4 correctly? After you import on Xcode project the file **libBVLinearGradient.a** are on *Products* folder: http://i.imgur.com/5kPDLL0.png?1

**Comment by jasecoop** [comment]
@jadsonlourenco Thanks for helping... In Step 2? What files do I add?

The whole project folder from mode_modules?

**Comment by jasecoop** [comment]
Yep. Step 2 it wasn't clear I was to add react-native-linear-gradient folder from node_modules.

Then I found libBVLinearGradient.a like you mentioned.

Thanks for your help, I got it now :)

**Comment by jadsonlourenco** [comment]
@jasecoop good to know. Yes, some modules on React Native need do that, for IOS app, so, now you know how to use then. Have good day! :)

**Comment by nickhudkins** [comment]
thanks @jadsonlourenco :+1:
