### ISSUE TITLE
Error: can't find the package for 1.1.0

### ISSUE THREAD

**Issue by pedramsaleh** [brentvatne/react-native-linear-gradient#21]
I did a fresh install of this package (with RN 0.8.0) when migrating my code to a new project.  I kept getting an error that React couldn't find the linear-gradient package (saying to restart the packager if I'm sure it's there).  I restarted the packager, uninstalled and re-installed the linear-gradient package and still got the same error.  Then I saw that my previous project had 0.3.2 in my previous package.json file, and it was now 1.1.0-alpha.  I reverted back to 0.3.2 and that fixed the error.  Just thought I'd report that in case it wasn't intended functionality.

**Comment by nickhudkins** [comment]
Thanks @pedramsaleh, 1.0.0-alpha and newer are to be used with ^RN 0.12 so this appears to be correct behavior. Glad you got your issue sorted :)

**Comment by pedramsaleh** [comment]
OK, good to know.  Maybe that should be specified in the install instructions or release notes, since right now it just says "RN 0.12.0 is now supported".  Perhaps it should say 'RN 0.12.0 is now **required**".

**Comment by nickhudkins** [comment]
Good call :) feel free to submit a PR and I would happily accept, otherwise i'll get this done first thing tomorrow!

**Comment by brentvatne** [comment]
@nickhudkins :rocket: :guitar:
