### ISSUE TITLE
[BUG] RN v0.12 & processColor

### ISSUE THREAD

**Issue by yelled3** [brentvatne/react-native-linear-gradient#22]
@brentvatne  due to https://github.com/facebook/react-native/issues/3300
when passing `colors` array to `LinearGradient` you must run `processColor` on each color, e.g: 
```js
<LinearGradient colors={[processColor('#4c669f'), processColor('#3b5998')]} >
// ...
</LinearGradient>
```
the crash happens in 
https://github.com/brentvatne/react-native-linear-gradient/blob/master/BVLinearGradient.m#L22

maybe `- (void)setColors:(NSArray *)colorStrings` should do the  conversion?

**Comment by nickhudkins** [comment]
@yelled3 can you let me know which version of react-native-linear-gradient you are running? this was resolved in the 1.0.0-alpha release.

If you are running 0.3.2 you are correct that you will need to run processColor. have a look here: https://github.com/brentvatne/react-native-linear-gradient/blob/master/index.ios.js#L16
for the relevant code.

Thanks,
Nick

**Comment by yelled3** [comment]
@nickhudkins you're correct, I was using `0.3.2`.
I upgraded to latest (`1.1.0-alpha`) and everything works great.

cheers :-)

**Comment by nickhudkins** [comment]
Awesome :) Glad to hear it. 1.1.0-alpha also supports Android. Currently in alpha due to the fact that I have only used it on a single project.
