### ISSUE TITLE
android folder not installing on npm install

### ISSUE THREAD

**Issue by sellds4** [brentvatne/react-native-linear-gradient#23]

**Comment by nickhudkins** [comment]
hey @sellds4 could you provide some additional information? How was the project started? What version of react-native are you using?

**Comment by sellds4** [comment]
Sorry, probably should have provided more details, react-native v0.1.5.  I used the react-native init command to start the project, then npm install react-native-linear-gradient --save. I physically copied the android folder over from the zip so the project would build.
I'm now getting an error in the project with the LinearGradient component, telling me it expected dynamic type 'int64', but had type 'string'.

I'm on Linux 14 Nadia.

**Comment by lalith26** [comment]
Hi

I am also facing the same issue. Android Folder is not getting installed on running 'npm install'.
This is the error message from Gradle:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-linear-gradient : Configuration with name 'default' not found.

When I checked my node_modules, there was no 'android' folder.
Then I saw the releases tab of this repo and downloaded the zip file. The android folder is not present there too.

I am using react-native version v0.12.0
Can you please help?

**Comment by richarddewit** [comment]
I am having the same issue, `npm i -S react-native-linear-gradient` does not install the `android` folder along with it.

`npm` installs `v0.3.2` by default, this version doesn't contain the folder.
The versions `1.0.0-alpha` and `1.1.0-alpha` **DO** contain `android` folder, but this isn't installed by npm, I guess because it's prefixed with `alpha`.

**Comment by nickhudkins** [comment]
@richarddewit this is correct. specifying @1.1.0-alpha or @1.0.0-alpha will get you an android supported version. Once we have had enough time and tested thoroughly it will become a non-alpha and you will not need to specify. In the meantime, please make sure if you would like android support to install @1.1.0-alpha.
