### ISSUE TITLE
Odd - Example code failing

### ISSUE THREAD

**Issue by GantMan** [brentvatne/react-native-linear-gradient#25]
Basically using your example values, but I'm getting this.

![simulator screen shot oct 16 2015 12 11 12 pm](https://cloud.githubusercontent.com/assets/997157/10548281/170f74b0-73ff-11e5-8340-02f21c99fcd6.png)

**Comment by GantMan** [comment]
Hrmmm, looks like there's a layer missing, bc this works:
![image](https://cloud.githubusercontent.com/assets/997157/10548401/1bb4472e-7400-11e5-9664-1b30a2846b4f.png)

**Comment by GantMan** [comment]
Looks like this is fixed when I pointed at GitHub, instead of whatever version `npm` gave me.

Thanks for a great component.  See PR #26 where I clarify a few items for others.

**Comment by nickhudkins** [comment]
hey @GantMan can you give this a shot again with `npm install react-native-linear-gradient@latest` ?
You should end up with 1.1.0-alpha (which is where master currently is)

**Comment by GantMan** [comment]
That did work.  Would you like me to update my pull-request to give this advice?

**Comment by brentvatne** [comment]
@GantMan - sure! thanks
