### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react-native-linear-gradient'

### ISSUE THREAD

**Issue by JeremDsgn** [brentvatne/react-native-linear-gradient#28]
Hi!

I tried a lot to work with linear-gradient, but didn't find any solution to make it real.

I've tried : 
- `"linear-gradient": "0.3.2"` and `"react-native": "^0.12.0"` -> it didn't work + issue #25 

- `"linear-gradient": "0.3.2"` and `"react-native": "^0.13.2"` -> it didn't work + issue #25 

- `"linear-gradient": "1.0.0-alpha"` and `"react-native": "^0.12.0"` -> it didn't work + `Module not found: Error: Cannot resolve module 'react-native-linear-gradient'`

- `"linear-gradient": "1.0.0-alpha"` and `"react-native": "^0.13.2"` -> it didn't work + `Module not found: Error: Cannot resolve module 'react-native-linear-gradient'`

- `"linear-gradient": "brentvatne/react-native-linear-gradient"` and `"react-native": "^0.13.2"` -> it didn't work + Module not found: Error: Cannot resolve module 'react-native-linear-gradient'

- `"linear-gradient": "brentvatne/react-native-linear-gradient"` and `"react-native": "^0.13.2"` -> it didn't work + Module not found: Error: Cannot resolve module 'react-native-linear-gradient'

I don't know what to do right now, hope you can help.

Do not hesitate to ask more informations if needed.

**Comment by nickhudkins** [comment]
Hi @JeremDsgn, I just was able to run a new project (react-native 0.13.2) and (react-native-linear-gradient 1.1.0-alpha)

by doing the following:

```
1. npm install -g react-native-cli@latest
2. react-native init `bar` 
3. linked BVLinearGradient.a in the xcode project Build Settings
4. built xcode project
5. run `npm start` from `./bar`
```
This resulted in no errors, so I am guessing there is something else going on. 

Can you provide a simplified test case of this failing? Do you have a project somewhere I could take a look at?

- Nick

**Comment by JeremDsgn** [comment]
Hi!

By doing this `npm install -g react-native-cli@latest` you didn't install `react-native: 0.13.2`, I think, but I don't know if it's really important.

Since El capitan update, Xcode is crashing so much, can't launch the project right, I update as soon as possible and try to produce a simple fail case.

**Comment by richarddewit** [comment]
`1.0.0-alpha` doesn't have an `index.js` and the `package.json` doesn't have a `main` key set. You could do however, require the `index.ios.js` and `index.android.js`.

**Comment by brentvatne** [comment]
Hi people, I have updated to 1.3.0 and these problems should be resolved

**Comment by samerdernaika** [comment]
in my case i found a space while importing it , i removed the space and it works like a charm
