### ISSUE TITLE
Stays white

### ISSUE THREAD

**Issue by dvine-multimedia** [brentvatne/react-native-linear-gradient#3]
Hi Brent.

First, thanks a lot for the very helpful components you are building!
I can't get the gradient to work though, the box stays white.
I'm pretty sure I included and compiled everything correctly. And when I set wrong values to the colors attribute I get the correct errors (e.g. not an array, not a color etc)

Any ideas, where I could have gone wrong? I'm using react-native 0.4.2 and iOS SDK 8.3.

Thanks for your help.

Cheers
Georg

**Comment by dvine-multimedia** [comment]
I'm completely new to Objective-C and no idea if this is of any relevance, but in BVLinearGradient.m Line 22:23 XCode shows a warning
Incompatible pointer types sending 'CGColorRef' (aka 'struct CGColor *') to parameter of type 'id'

**Comment by brentvatne** [comment]
Hey @dvine-multimedia! Can you post the code that you're using? I'll give it a try :)

**Comment by dvine-multimedia** [comment]
Hi Brent.

I figured it out. The LinearGradient box inherits the background color from it's paren't and this overrides the gradient. If I manually set it back to "transparent" it works. Maybe the gradient could overrider the background color instead?

**Comment by brentvatne** [comment]
Ah, that's a good idea, could you submit a PR for that?

**Comment by johnnythecakes** [comment]
Hey Brent,

Thanks for the demo app and components! I'm having the same issue as @dvine-multimedia but am unable to resolve using the backgroundColor: 'transparent' on the parent component mentioned above. I wonder if the Background Color Propagation update in v0.6.0-rc didn't break something? https://github.com/facebook/react-native/releases/tag/v0.6.0-rc

Thanks,
Zach

**Comment by johnnythecakes** [comment]
scratch v0.6.0-rc being my problem...not using that release

**Comment by brentvatne** [comment]
@johnnythecakes - what if you set the `style={{backgroundColor: 'transparent'}}` directly on the gradient itself? If that fixes it, I'll make that the default behaviour :smile:

**Comment by unknownexception** [comment]
@brentvatne last trick works for me, thanks

**Comment by nickhudkins** [comment]
@brentvatne is this something you have in the works? If not, feel free to assign to me and I'll address this week.
