### ISSUE TITLE
JSON Value can't be converted to number

### ISSUE THREAD

**Issue by kcrao** [brentvatne/react-native-linear-gradient#30]
Hi I was able to install your nom. 
However, when I try to use it I get the following error with the sample code provided.
JSON value '#4c669f' of type NSString cannot be converted to NSNumber

**Comment by nickhudkins** [comment]
Could you please provide your RN version and the version of react-native-linear-gradient that you are using.

**Comment by kcrao** [comment]
Thanks Nick,  I've pasted it below.
 "react-native": "^0.12.0",
  "react-native-linear-gradient": "^0.3.2",

**Comment by nickhudkins** [comment]
please use react-native-linear-gradient@1.1.0-alpha to solve this issue.

**Comment by JonathanWi** [comment]
I think the link you provided is the wrong one :)
