### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by anttimo** [brentvatne/react-native-linear-gradient#33]
Hi, could you please include a license to this project?

Thanks!

**Comment by nickhudkins** [comment]
@brentvatne preference here?

**Comment by tomauty** [comment]
+1

**Comment by brentvatne** [comment]
@nickhudkins - MIT works

I really don't care what people do with this :)

**Comment by tomauty** [comment]
Awesome, thanks. Just wanted to be sure :)

**Comment by brentvatne** [comment]
OK added to README!
