### ISSUE TITLE
Bad performance with TouchableHighlight 

### ISSUE THREAD

**Issue by jforaker** [brentvatne/react-native-linear-gradient#37]
I am using the plugin for a subtle dark gradient over an `<Image>` with white text. I have noticed with the plugin, touch performance on the cells has decreased significantly. Meaning, some touches are not registered and touches in general are unreliable.

Am I missing something? Or is performance of TouchableHighlight hindered by this plugin?

![image](https://cloud.githubusercontent.com/assets/2042031/11136678/ab208b82-897e-11e5-8a72-dbefd23576b2.png)

Below represents a cell of a `<Listview />` component.

```
				<TouchableHighlight onPress={this.props.onSelect}>

					<View style={styles.container}>

						<Image source={{uri: this.props.eventData.photo}} style={styles.bg}/>

						<LinearGradient
							colors={['transparent', 'black']}
							style={styles.linearGradient}/>

						<View style={styles.postDetailsContainer}>
							{featured}
			
                                   .............
```

Styles:

```
var styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'black',
    },
    bg: {
        position: 'absolute',
        left: 0,
        top: 0,
        width: windowSize.width,
        height: windowSize.height / 3
    },
	linearGradient: {
		position: 'absolute',
		left: 0,
		bottom:0,
		width: windowSize.width,
		height: windowSize.height / 3
	},
    postDetailsContainer: {
        height: windowSize.height / 3
    },
.....
```

**Comment by rreusser** [comment]
Have you tried [`shouldRasterizeIOS`](https://facebook.github.io/react-native/docs/view.html#shouldrasterizeios) (and [`renderToHardwareTextureAndroid`](https://facebook.github.io/react-native/docs/view.html#rendertohardwaretextureandroid) if you're into that stuff)? It tells the view to rasterize children instead of redrawing each time. If I understand it correctly (which, honestly, I likely don't!), this changes a bunch of redraws during an animation into just a compositing operation. Helped a ton for us in a somewhat similar situation.

**Comment by rreusser** [comment]
Yeah, maybe just:

```javascript
<View style={styles.container} shouldRasterizeIOS={true}>
```

That should rasterize the gradient and then the parent will change its opacity.

**Comment by jforaker** [comment]
I had no idea about that property! Good thinking..  And yes I am on Android :dizzy_face: 

Initial findings look promising, which makes me happy, but I'm not able to test fully at the moment. Will report back tonight.

**Comment by rreusser** [comment]
Awesome. Yeah, it prevented what basically would have been a show-stopper otherwise. Shadows + ListView were prohibitively slow without it, totally fine with it.

**Comment by brentvatne** [comment]
On Android the equivalent is: https://facebook.github.io/react-native/docs/view.html#rendertohardwaretextureandroid

**Comment by brentvatne** [comment]
nice :)

**Comment by jforaker** [comment]
I'm going to close this out, as I found a temporary work around that I am okay with. Using a combo of @rreusser's method and wrapping it with `TouchableWithoutFeedback` seems to help. Though it is not perfect, there are still times where I have to press in different spots to get it to fire, but its better than before.

```
			<View>
				<TouchableWithoutFeedback style={styles.container} onPress={this.props.onSelect}>
					
					<View style={styles.container} renderToHardwareTextureAndroid={true}>

						<Image source={{uri: this.props.eventData.photo}} style={styles.bg}/>

						<LinearGradient
							colors={['transparent', 'black']}
							style={styles.linearGradient}/>

						<View style={styles.postDetailsContainer}>
                                               ....
```

**Comment by mnlbox** [comment]
@jforaker are you found any final way to fix this?
I have same issue and `onPress` take some second to fire. 😢

**Comment by mnlbox** [comment]
**/CC:** @dgladkov, @brentvatne
