### ISSUE TITLE
not working with react-native 0.4.3

### ISSUE THREAD

**Issue by meric426** [brentvatne/react-native-linear-gradient#4]
due to breaking changes in https://github.com/facebook/react-native/releases/tag/v0.4.3

**Comment by brentvatne** [comment]
@meric426 - did you get this working?

**Comment by meric426** [comment]
yes @brentvatne, my npm wouldn't update react-native-linear-gradient to the newest version because i had some other packages requiring an older version of react-native. So the issue was with me :smile:

**Comment by brentvatne** [comment]
good to know, thanks for the follow up @meric426 :smile:
