### ISSUE TITLE
compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by olitomas** [brentvatne/react-native-linear-gradient#44]
I followed the instructions for Android setup and get this error when trying to build and run.

I am using Genymotion emulator, react-native 0.14.2 and react-native-linear-gradient 1.1.0-alpha

![trouble](https://cloud.githubusercontent.com/assets/6918659/11530159/3f9875ca-98ea-11e5-911d-99fcdc8d3f86.jpg)

**Comment by brentvatne** [comment]
Hi there! This should work properly on 0.16.0 and linear-gradient 1.3.0. Sorry about that!

**Comment by sampurcell93** [comment]
Hi, I am running native 0.17.0 and have installed 1.3.0 of this package (confirmed in node_modules) - but I am still getting the same error that @olitomas reported. Any ideas?

**Comment by Pandzinho** [comment]
I'm also getting this error. @brentvatne any plans to revisit this issue?
