### ISSUE TITLE
Left to Right Gradient?

### ISSUE THREAD

**Issue by bradbumbalough** [brentvatne/react-native-linear-gradient#45]
I've been playing with the combination of `location`, `start`, and `end` props but can't figure out how to implement a left to right gradient. Any thoughts?

Thanks!

**Comment by nickhudkins** [comment]
start is [x,y] (proportional) end is same so:

`      <LinearGradient colors={['#514A9D', '#24C6DC']}
                      start={[0.0, 0.5]}
                      end={[1.0, 0.5]}
                      locations={[0.0, 1.0]}
                      style={styles.container}>
`

will do the trick!

![screen shot 2015-12-09 at 1 19 09 pm](https://cloud.githubusercontent.com/assets/299126/11694335/81f5674c-9e77-11e5-8af8-251272482e45.png)

**Comment by bradbumbalough** [comment]
Ok, I think I understand it now. Thanks for the fast reply!

On Wednesday, December 9, 2015, Nick Hudkins <notifications@github.com>
wrote:

> start is x,y <http://proportional> end is same so:
>
> <LinearGradient colors={['#514A9D', '#24C6DC']}
> start={[0.0, 0.5]}
> end={[1.0, 0.5]}
> locations={[0.0, 1.0]}
> style={styles.container}>
>
> will do the trick!
>
> [image: screen shot 2015-12-09 at 1 19 09 pm]
> <https://cloud.githubusercontent.com/assets/299126/11694335/81f5674c-9e77-11e5-8af8-251272482e45.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brentvatne/react-native-linear-gradient/issues/45#issuecomment-163347742>
> .
>


-- 
-Brad
Sent from my iPhone

**Comment by nickhudkins** [comment]
Woops! Looks like my explanation got butchered a little bit. Basically 0,0 is top left , 1,1 is bottom right.

:+1:

**Comment by gopinathrpt** [comment]
when i insert the code Error occur... can you help me pls
![screen shot 1939-09-21 at 10 59 06 am](https://user-images.githubusercontent.com/31948230/33868833-62950c1c-df2b-11e7-9fc8-eff3017c5afb.png)


This is my code


Program:

<LinearGradient colors={['#514A9D', '#24C6DC']}
                        start={[0.0, 0.5]}
                        end={[1.0, 0.5]}
                        locations={[0.0, 1.0]}
                        style={styles.container}>
                        <View style={styles.buttonText}>
                            <Calendar
                                theme={{
                                    backgroundColor: 'transparent',
                                    calendarBackground: 'transparent',
                                    textSectionTitleColor: '#fff',
                                    selectedDayBackgroundColor: 'yellow',
                                    selectedDayTextColor: 'red',
                                    todayTextColor: '#00adf5',
                                    dayTextColor: '#fff',
                                    textDisabledColor: '#d9e1e8',
                                    arrowColor: '#fff',
                                    monthTextColor: '#fff',
                                    textDayFontSize: 12,
                                    textMonthFontSize: 16,
                                    textDayHeaderFontSize: 16,
                                    currentDayCircle: {
                                        backgroundColor: 'blue',
                                    },
                                }}
                                hideExtraDays={true}
                                hideArrows={true}
                                onDayPress={(day) => {
                                    //console.log('selected day', day) 
                                }}
                            />
                            <View>
                            </View>
                        </View>
                    </LinearGradient>

**Comment by sairohithA007** [comment]
I faced the same issue. I just changed the `start` to `startPoint` and `end` to `endPoint` in LinearGradient tag. It worked for me.
