### ISSUE TITLE
[Android] start/end are ignored

### ISSUE THREAD

**Issue by frantic** [brentvatne/react-native-linear-gradient#48]
Code: https://gist.github.com/frantic/52ad2025cc10a5be238a
Screenshot:

<img width="963" alt="screen shot 2015-12-15 at 11 15 16 am" src="https://cloud.githubusercontent.com/assets/192222/11821198/24f27918-a31d-11e5-9436-1c3f73744b32.png">

**Comment by bodyflex** [comment]
+1
