### ISSUE TITLE
[Android] Can't have more than 1 type of gradient

### ISSUE THREAD

**Issue by frantic** [brentvatne/react-native-linear-gradient#49]
See screenshot - 2 views are supposed to have different gradients but they are both rendered the same way. Sometimes I get 2 blue buttons, sometimes 2 green buttons. Works on iOS.

Code: https://gist.github.com/frantic/741a824879e34c1ad375

<img width="955" alt="screen shot 2015-12-15 at 11 09 10 am" src="https://cloud.githubusercontent.com/assets/192222/11821321/b9195832-a31d-11e5-94d3-beadaaeb67ba.png">

![image](https://cloud.githubusercontent.com/assets/192222/11821343/def9c3e8-a31d-11e5-92dd-cb390c6a3643.png)

**Comment by mattds** [comment]
Seems to be that in LinearGradientView e.g. mColors etc are declared as static so shared for all instances, removing the static keyword in this file fixed this for me. Also for the other android issue I think changing  mLocations = locations; to mLocations = locations != null ? locations : mLocations; in drawGradient is what is needed, perhaps it's worth testing on your side to confirm.

**Comment by brentvatne** [comment]
Looks like this is fixed by #51 :)
