### ISSUE TITLE
borderRadius no longer working with 0.4.2+

### ISSUE THREAD

**Issue by jessepollak** [brentvatne/react-native-linear-gradient#5]
With 0.4.2, the `borderRadius` property on the Linear Gradient no longer works. I think it may be related to facebook/react-native#1235.

Any thoughts?

**Comment by brentvatne** [comment]
@jessepollak - Yeah this is an unfortunate problem, it is related to that issue indeed. I'll let you know if I come up with a good workaround

**Comment by jessepollak** [comment]
cool, thanks! I'm just going with squares instead of circles for everything now :P

**Comment by brentvatne** [comment]
This is fixed now in 0.5 and higher!
