### ISSUE TITLE
1.3.1 not working on on Android

### ISSUE THREAD

**Issue by bodyflex** [brentvatne/react-native-linear-gradient#52]
trying to use version 1.3.1 on a real device (Nexus 5 running Android 6.0.1) gives the following error
![screenshot_20160115-103749](https://cloud.githubusercontent.com/assets/7894563/12349011/fcdc9c54-bb74-11e5-9251-994369167f60.png)

haven't tried the emulator. 1.3.0 doesn't crash like this.

EDIT: oh and I'm using RN 0.17.0

**Comment by ramilushev** [comment]
I'm getting the same error on RN 0.16.0 ...

**Comment by brentvatne** [comment]
cc @frantic

**Comment by dgladkov** [comment]
Reverting 75da98fff4b2d2d75650c2996e2681c57f18235d solved exception on Android for me. However, `LinearGradientView` changes introduced in a2503d06662ee43f4a439b827e9a010fd7702e80 and 872f504797e2f941c51e14ef8f89db37a3e6613a have broken linear gradient in my project and I'm not sure how to fix it yet.

**Comment by dgladkov** [comment]
I think I found the problem. Will send a pull request tomorrow
