### ISSUE TITLE
A problem occurred configuring project ':react-native-linear-gradient' | Fix reporting

### ISSUE THREAD

**Issue by agutoli** [brentvatne/react-native-linear-gradient#54]
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-linear-gradient'.
   > Could not resolve all dependencies for configuration ':react-native-linear-gradient:_debugCompile'.
      > Could not find com.android.support:appcompat-v7:23.0.1.
        Searched in the following locations:
            file:/Users/agutoli/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
            file:/Users/agutoli/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
            https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
            https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
        Required by:
            VivoFama:react-native-linear-gradient:unspecified > com.facebook.react:react-native:0.12.0
      > Could not find com.android.support:support-v4:21.0.3.
        Searched in the following locations:
            file:/Users/agutoli/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
            file:/Users/agutoli/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
            https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
            https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
            https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
            https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
        Required by:
            VivoFama:react-native-linear-gradient:unspecified > com.facebook.react:react-native:0.12.0 > com.facebook.fresco:fresco:0.6.1 > com.facebook.fresco:drawee:0.6.1
            VivoFama:react-native-linear-gradient:unspecified > com.facebook.react:react-native:0.12.0 > com.facebook.fresco:fresco:0.6.1 > com.facebook.fresco:imagepipeline:0.6.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by agutoli** [comment]
I managed to solve this link:http://stackoverflow.com/questions/18559660/android-gradle-build-fails-could-not-find-com-google-androidsupport-v4r18

"You need to install Android Support Repository from SDK manager. After that Gradle will be able to resolve support libraries from ${SDK_HOME}\extras\android\m2repository\".

**Comment by frantic** [comment]
Thanks @agutoli!

**Comment by rptwsthi** [comment]
It is happening with me:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-linear-gradient'.
> Failed to find Build Tools revision 26.0.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 2s
Failed to find Build Tools revision 26.0.3
```
