### ISSUE TITLE
Bypass touch events?

### ISSUE THREAD

**Issue by aksonov** [brentvatne/react-native-linear-gradient#59]
I want to use linear gradient over map control but want to still able to swipe map, is it possible?

**Comment by dgladkov** [comment]
LinearGradient component is rendered as a View and accepts all View props. You can use [View.pointerEvents](https://facebook.github.io/react-native/docs/view.html#pointerevents) prop set to `"none"` to pass touch events to underlying components.

**Comment by artemkapleev** [comment]
@aksonov could you please share your experience, did `pointerEvents` work for you?
