### ISSUE TITLE
[Android] Native component for "BVLinearGradient" does not exist

### ISSUE THREAD

**Issue by starInEcust** [brentvatne/react-native-linear-gradient#63]
I got this warning, 
Warning: Native component for "BVLinearGradient" does not exist
rnTest/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js
and all I get is a red border around it.
my OS is win10.

**Comment by starInEcust** [comment]
sorry,I forgot to rebuild the app.

**Comment by darmie** [comment]
I have rebuilt my app several times, but I still get this error.

**Comment by cciszak** [comment]
@darmie maybe your install didnt work correctly. Try to follow manual install steps from the main page and see if that resolves your problem.

**Comment by JeroenNelen** [comment]
I'm also getting this error. @darmie did you find a solution?

**Comment by darmie** [comment]
I have stopped using react-native, there seems to be alot of friction in
getting stuff done with it.

**Comment by JeroenNelen** [comment]
@darmie I see, thanks for the reply though!

**Comment by kis25791** [comment]
Hi any solution for this issue till now?

**Comment by aminemboulouma** [comment]
@kis25791 The solution is just to rebuild the app as @starInEcust said :)

**Comment by hughsaffar** [comment]
The following worked for me:
If you already edited the ``MainApplication.java`` for the other packages, there is a chance that the ``react-native link`` cannot parse and add ``new LinearGradientPackage()``. Follow the manual installation instruction for Android and edit your ``MainApplication.java`` file.

**Comment by ionush** [comment]
this was my problem in Android. It was in the wrong .java file because of my version of react-native.
Check the docs for installation
