### ISSUE TITLE
rnpm doesn't seem to install anything for iOS

### ISSUE THREAD

**Issue by faceyspacey** [brentvatne/react-native-linear-gradient#67]
I only get 2 messages that android dependencies were installed:

```
rnpm-link info Linking react-native-linear-gradient android dependency 
rnpm-link info Android module react-native-linear-gradient is already linked 
```

and then see no linked binaries in Xcode.

**Comment by brentvatne** [comment]
@Kureev - any idea? I didn't set this up for this project so I'm not sure what is wrong

**Comment by Kureev** [comment]
I think @grabbou knows more about iOS part

**Comment by grabbou** [comment]
It's likely an issue with @faceyspacey project, not linear-gradient itself (I am using it happily). What's your xcodeproj name @faceyspacey ? Does linking of other projects work? Anyway - if you could close this issue and move it to #rnpm repository, it'd be cool!

**Comment by dgladkov** [comment]
Just tested `rnpm link` on the fresh test project with latest rnpm, linking both Android and iOS works fine for me. It appers that this was rnpm problem and it's already fixed, so I'm closing this issue.
