### ISSUE TITLE
Inside TouchableOpacity and TouchableHighlight doesn't render on Android

### ISSUE THREAD

**Issue by andrewtoth** [brentvatne/react-native-linear-gradient#68]
Wrapping a LinearGradient component inside a TouchableOpacity does not render anything on Android. It renders fine on iOS. When wrapping in a TouchableHighlight, an error is shown stating that LinearGradient must implement setNativeProps. Wrapping it instead inside a View, then inside a TouchableHighlight results in it not rendering as well on Android, but rendering fine on iOS.

**Comment by andrewtoth** [comment]
Fixed in 0.22

**Comment by rayray-py** [comment]
save problem in 2.2.0
