### ISSUE TITLE
<Text> has transparent background inside of <LinearGradient />

### ISSUE THREAD

**Issue by ericmasiello** [brentvatne/react-native-linear-gradient#69]
I tried out several of the sample code examples on the readme.md file. Every one of them produced a nice gradient, however the `<Text />` component inside the `<LinearGradient />` is always transparent. The effect is that the linear gradient has a rectangle cut out of it.

Example: 
<img width="487" alt="screen shot 2016-03-23 at 7 51 21 pm" src="https://cloud.githubusercontent.com/assets/3525886/14004475/cb614480-f130-11e5-8721-7d39087c70ce.png">

I'm on React-Native v 0.22.2 and React Native Linear Gradient 1.5.2

Below is my source code:

```
import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  View,
  TouchableOpacity
} from 'react-native';
var LinearGradient = require('react-native-linear-gradient');

class RNGradient extends Component {
  login(){

  }

  render() {
    return (
      <View style={styles.container}>

        <TouchableOpacity onPress={this.login}>
          <LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']} style={styles.linearGradient}>
            <Text style={styles.buttonText}>
              Sign in with Facebook
            </Text>
          </LinearGradient>
        </TouchableOpacity>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'red',
  },
  linearGradient: {
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
  },
  buttonText: {
    fontSize: 20,
    fontFamily: 'Gill Sans',
    textAlign: 'center',
    color: '#ffffff',
    margin: 10,
    opacity: 0.8,
  },  
});

AppRegistry.registerComponent('RNGradient', () => RNGradient);
```

**Comment by brentvatne** [comment]
On the text you will need to set `color: 'transparent'` -- for information on why see the "Background Color Propagation" section of the [react-native 0.6.0-rc release notes](https://github.com/facebook/react-native/releases/tag/v0.6.0-rc) :)

**Comment by ericmasiello** [comment]
Ah! Thank you. I didn't think Text supported background color. Thanks for clarifying.

**Comment by brentvatne** [comment]
:)
