### ISSUE TITLE
Appears to be broken with RN 22 on Android

### ISSUE THREAD

**Issue by ilanasufrin** [brentvatne/react-native-linear-gradient#70]
I've been using this with my iOS app just fine and now I'm trying to port everything over to Android (RN 22). No gradient appears, it just seems to be a transparent view. There are also no relevant console errors.

Any ideas? Thanks for your help!

Edit: The gradient does not work on a Nexus 6 running API 23 but it *does* work with a Nexus One running the same API. Both Android emulators. It does not work with my Samsung Galaxy S6 physical device. Has anybody else come across the same problem?

**Comment by mmmurf** [comment]
it is just showing a red border, no gradient (IOS) with RN 22... just installed it so there is a chance I've done something incorrectly, however just using the example params.

**Comment by mak2014** [comment]
I am having exact same issue, no gradient with RN 0.22. Any ideas?

**Comment by ilanasufrin** [comment]
Is anybody else having the issue on Android? It's working for me on iOS

**Comment by adam-jakiela** [comment]
+1

**Comment by zerko** [comment]
Setting individual border radii with latest release fixes red box with border radius for me.

**Comment by dgladkov** [comment]
Can you please verify that the problem exists in version 1.5.6?

**Comment by adam-jakiela** [comment]
Turns out rnpm didn't link the package to my Android project. Once I manually included it in the Android project everything worked fine.

**Comment by dgladkov** [comment]
@adam-jakiela Can you please check that you are using latest version of rnpm? I just tried it on a demo project and rnpm links the package for both iOS and Android for me.

**Comment by magicspon** [comment]
+1

**Comment by munzur** [comment]
Not working on android. (used with rnpm) As said before there are only red borders.

**Comment by jasonalmaturner** [comment]
`react-native@0.29.2` is supposed to fix `rnpm link` for Android. It still didn't work for me. I was able to manually link by editing the `MainApplication.java` file instead of the `MainActivity.java` file.

```
package com.navi;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import com.BV.LinearGradient.LinearGradientPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new LinearGradientPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

**Comment by KakarN** [comment]
I too had the same problem. This is how I solved my problem:

1. `npm install react-native-linear-gradient --save`
2. In android/settings.gradle
```
...
include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')
```
3. In android/app/build.gradle add:
```
dependencies {
   ...
   compile project(':react-native-linear-gradient')
}
```
4. In android/app/src/main/java/com/{YOUR_APP_NAME}/MainApplication.java (react-native 0.40.0) add:
```
//...
import com.BV.LinearGradient.LinearGradientPackage; // <--- This!
//...
@Override
protected List<ReactPackage> getPackages() {
 return Arrays.<ReactPackage>asList(
   new MainReactPackage(),
   new LinearGradientPackage() // <---- and This!
 );
}
```
