### ISSUE TITLE
Separate borderRadius per corner not supported

### ISSUE THREAD

**Issue by andreialecu** [brentvatne/react-native-linear-gradient#74]
It looks like `borderTopLeftRadius` and the like are not properly supported. Only `borderRadius` is.

On Android at least, haven't checked iOS yet.

**Comment by dgladkov** [comment]
There is a known problem in Android with child views pushing through their parent's rounded corners. Solution included in the project was writthen before per corner border radii were introduced, so it just applies parent's borderRadius on NativeLinearGradient element
https://github.com/brentvatne/react-native-linear-gradient/blob/895cb02d31970be0558fc0d59925f45e840a7a73/index.android.js#L19

I will look at this issue this week, but if you are interested in contributing to the project, your help would be welcome:)

**Comment by andreialecu** [comment]
Well, I fixed it in #75. :)
