### ISSUE TITLE
Native controls not working on master

### ISSUE THREAD

**Issue by corbt** [brentvatne/react-native-linear-gradient#78]
Currently, native controls on iOS are broken in the master branch of this repository (I'm using master because I need the functionality in https://github.com/brentvatne/react-native-video/pull/181).

Expected behavior: an embedded video with native controls will have the controls appear, and then disappear while playing.

Actual behavior: No controls appear on the video at any time. Tapping the video causes the view to zoom in on the video.

Steps to reproduce: open the VideoPlayer example in the iOS simulator, set the controls type to "controls" and observe that no controls appear. I've also verified this is broken in my project.

Version 0.7.1 does work, but I wasn't able to track down the commit that breaks this quickly because there have been significant periods in this repository's history when the example was broken.

**Comment by dgladkov** [comment]
This is repository of `react-native-linear-gradient`, I think this issue belongs to another project:)

**Comment by corbt** [comment]
Whoops sorry, got my wires crossed somewhere.
