### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by olivierlesnicki** [brentvatne/react-native-linear-gradient#8]
it says:
```
Click on BVLinearGradient.xcodeproj in Libraries and go the Build Phases tab. 
```
instead of
```
Click on BVLinearGradient.xcodeproj in Libraries and go the Build Settings tab. 
```
under
https://github.com/brentvatne/react-native-linear-gradient/#add-it-to-your-project

**Comment by fatuhoku** [comment]
@olivierlesnicki it's probably more efficient to just submit a pull request for `README.md` with the correction in it the next time!

**Comment by brentvatne** [comment]
@fatuhoku - totally :smile:
