### ISSUE TITLE
Crash on 0.25.1

### ISSUE THREAD

**Issue by bendellarocco** [brentvatne/react-native-linear-gradient#83]
I am getting a crash when using this on .25.  It has been working for months on .19.  After the upgrade it crashes everytime.

implementation: 
<LinearGradient
      start={[0.5, 0.25]} end={[0.5, 1.]}
       colors={['transperant', 'black']}
       style={styles.linearGradient}>
</LinearGradient>

style:
  linearGradient: {
    flex: 1,
    backgroundColor: "transparent",
    opacity: .9
  },

error message:
[RCTConvert.m:449] Error setting property 'colors' of BVLinearGradient with tag #578: JSON value '<null>' of type NSNull cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?
2016-05-23 18:42:09.603 MassTuning[17257:285706] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

**Comment by bendellarocco** [comment]
after further investigation it was due to me using transparent as one of the values.  I was able to do this before to get a  black to nothing transition.  I cant anymore without a crash

**Comment by dgladkov** [comment]
Just checked transparent color option on both Android and iOS, it works as expected. There's a typo in your example that is probably the root of the problem:

colors={['**transperant**', 'black']}

**Comment by bendellarocco** [comment]
Wow. How has this been working on iOS for months?!  Thanks lol.
