### ISSUE TITLE
Functional refactor breaks `Animated` support

### ISSUE THREAD

**Issue by oblador** [brentvatne/react-native-linear-gradient#90]
Hi, 

With https://github.com/brentvatne/react-native-linear-gradient/commit/366239e441a40d329fad7defb775f256f420d448 this component was refactored into a functional component. I like that style, however it does not support the `ref` prop and thus it's not possible to use `Animated.createAnimatedComponent` with this component. If you want to keep supporting this use case I'm happy to submit a PR.

**Comment by dgladkov** [comment]
Hi,

Didn't realize that functional components do not support refs, sorry for breaking your code:(

I would like to support refs for sure, would gladly accept a PR that changes functional components to ES2015 classes
