### ISSUE TITLE
Produce horizontal Gradient

### ISSUE THREAD

**Issue by KishPatel1996** [brentvatne/react-native-linear-gradient#98]
what's the best way to produce a horizontal gradient?

Thanks in advance!

**Comment by luisfuertes** [comment]
try add prop `start={[0, 1]} end={[1, 0]}`

**Comment by KishPatel1996** [comment]
Thanks for the response, but that produces a diagonal gradient, not necessarily a horizontal one.

**Comment by Thorbenandresen** [comment]
Try adding the props `colors={['green', 'blue']}`

**Comment by telnicky** [comment]
I was able to get a horizontal gradient by using the props `start={[0, 0]} end={[1, 0]}`.

**Comment by KishPatel1996** [comment]
@telnicky That was it!  Thanks.

**Comment by alzalabany** [comment]
this is outdated.

**Comment by gopinathrpt** [comment]
<LinearGradient colors={['#00B4BF', '#137EB0']}
                           start={{ x: 0, y: 1 }}
                           end={{ x: 1, y: 1 }}
                            style={styles.linearGradient}>




![screen shot 1939-09-30 at 1 58 55 pm](https://user-images.githubusercontent.com/31948230/34247018-065f36ba-e657-11e7-9e4d-763bdabf2c5d.png)


i cant set start and end

please any one help me

**Comment by lewistaylor** [comment]
@gopinathrpt See #253

**Comment by mohammadsufyan** [comment]
> Thanks for the response, but that produces a diagonal gradient, not necessarily a horizontal one.

Try x,y values according to following props:
start={{x: 0.0, y: 0.25}} end={{x: 0.5, y: 1.0}}

**Comment by pumanitro** [comment]
Tried a lot of combination but only this worked for me:

`        start={[1, 1]} end={[1, 0]}`
